### PR TITLE
Read Headers line by line until an empty line is found

### PR DESCRIPTION
**Pull request by FrankBakkerNl**
## Description

- Fix for issue where pasing if the headers also consumes the data of the first message if available. Now we only read the headers line by line and stop reading after the first blank line (CRLFCRLF) so the first message will still be available for processing later on.
- Also, because a message can now be available immediately, the MessageReceived callback could be called directly, so we need to set the State to 'Connected' before starting the ReceiveAndControllThread Thread. Otherwise inside the callback the State is still 'Connecting' and we cannot send messages from it.

## Motivation and Context

- Fixes nanoFramework/Home#1356.

## How Has This Been Tested?

I tested this for my own use case which connects to Home Assistant. Home Assistant sends a first message directly after connecting, which caused the original issue. Other scenario's I have not tested

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Comment by FrankBakkerNl** [comment]
@dotnet-policy-service agree

**Review by Feiko — APPROVED** [review]
Looks good @FrankBakkerNl, Thanks for this great contribution!

**Review by Feiko — APPROVED** [review]

**Comment by josesimoes** [comment]
All good then! Merging this.

**Comment by josesimoes** [comment]
@nfbot updatedependencies

**Comment by josesimoes** [comment]
@nfbot updatedependencies

**Review by josesimoes — APPROVED** [review]
LGTM!

**Pull request merged**
