### PR TITLE
Added support for custom Http Headers for Websocket

### PR DESCRIPTION
**Pull request by Feiko**
## Description
Option for adding custom headers to the Websockets.Client
small fix of bug when trying to close websocket that's already disposed (racing conditions) objectdisposedExpetion 

## Motivation and Context

You can now have extra control over custom headers. This can be used for authentication or other things. This makes the Client more usable. 

## How Has This Been Tested?

With websocket server and NF websocket Client.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
Nice improvement and great for the fix too!

**Comment by josesimoes** [comment]
@Feiko don't worry about the build failure. It's with our tool. Working on it.

**Comment by Feiko** [comment]
@josesimoes, Great! Yeah this will make the client side more use full I think.

**Comment by josesimoes** [comment]
@Feiko something to keep in mind for future PRs: we should have these "atomic" as much as possible. Main reason to be able to isolate changes and even make quick reverts, if needed.
In this case the fix should have been on it's own PR separated from the new feature. 😉

**Pull request merged**
